apiVersion: v1
kind: ReplicationController
metadata:
    name: myapp-rc 
    labels: 
        app: my-app
        type: front-end
spec:
    template: # Pod template, same structure pod-definition.yml

        metadata:
            name: myapp-pod
            labels:
                app: myapp
                type: front-end
        spec:
            containers:
                - name: nginx-container
                  image: nginx
    
    replicas: 3 # number of replicas

# kubectl create -f replication-definition.yml
# kubectl get replicationcontroller
# kubectl get pods